### ISSUE TITLE
Postcss error on generate

### ISSUE THREAD

**Issue by lrocher91** [prismicio/vue-essential-slices#15] opened 2021-03-30 00:59 UTC
I have an issue with postcss when i try to compile with `yarn generate` referencing the `FeatureTestimonials` slice :

```
ERROR in ./node_modules/vue-essential-slices/src/slices/FeatureTestimonials/index.vue?vue&type=style&index=0&lang=scss& (./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-essential-slices/src/slices/FeatureTestimonials/index.vue?vue&type=style&index=0&lang=scss&)
Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js):
ParserError: Syntax Error at line: 1, column 22
    at ~/node_modules/vue-essential-slices/src/slices/FeatureTestimonials/index.vue:1:282
    at Parser.error (~/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (~/node_modules/postcss-values-parser/lib/parser.js:162:20)
    at Parser.parseTokens (~/node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (~/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (~/node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (~/node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at ~/node_modules/postcss-custom-properties/index.cjs.js:333:24
    at ~/node_modules/@nuxt/postcss8/node_modules/postcss/lib/container.js:91:18
    at ~/node_modules/@nuxt/postcss8/node_modules/postcss/lib/container.js:74:18
    at Rule.each (~/node_modules/@nuxt/postcss8/node_modules/postcss/lib/container.js:60:16)
    at Rule.walk (~/node_modules/@nuxt/postcss8/node_modules/postcss/lib/container.js:71:17)
    at ~/node_modules/@nuxt/postcss8/node_modules/postcss/lib/container.js:79:24
    at Root.each (~/node_modules/@nuxt/postcss8/node_modules/postcss/lib/container.js:60:16)
    at Root.walk (~/node_modules/@nuxt/postcss8/node_modules/postcss/lib/container.js:71:17)
    at Root.walkDecls (~/node_modules/@nuxt/postcss8/node_modules/postcss/lib/container.js:89:19)
    at transformProperties (~/node_modules/postcss-custom-properties/index.cjs.js:330:8)
 @ ./node_modules/vue-essential-slices/src/slices/FeatureTestimonials/index.vue?vue&type=style&index=0&lang=scss& (./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-essential-slices/src/slices/FeatureTestimonials/index.vue?vue&type=style&index=0&lang=scss&) 4:14-456
 @ ./node_modules/vue-essential-slices/src/slices/FeatureTestimonials/index.vue?vue&type=style&index=0&lang=scss&
 @ ./node_modules/vue-essential-slices/src/slices/FeatureTestimonials/index.vue
 @ ./node_modules/vue-essential-slices/src/slices lazy ^\.\/.*\.vue$ namespace object
 @ ./node_modules/.cache/nuxt/prismic/sm-resolver.js
 @ ./node_modules/.cache/nuxt/index.js
 @ ./node_modules/.cache/nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/.cache/nuxt/client.js
```

If i comment the <style> part of the `FeatureTestimonials/index.vue` file, the error is gone.

Here is my package.json :
```
{
  "name": "website",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt-ts",
    "build": "nuxt-ts build",
    "start": "nuxt-ts start",
    "generate": "nuxt-ts generate",
    "lint:js": "eslint --ext \".js,.vue\" --ignore-path .gitignore .",
    "lint": "yarn lint:js",
    "slicemachine": "start-slicemachine --port 9999",
    "storybook": "nuxt storybook",
    "build-storybook": "nuxt storybook build"
  },
  "dependencies": {
    "@nuxt/typescript-runtime": "^2.0.1",
    "@prismicio/vue": "^2.0.11",
    "core-js": "^3.9.1",
    "nuxt": "^2.14.12",
    "nuxt-sm": "^0.0.6",
    "prismic-javascript": "^3.0.2",
    "vue-essential-slices": "^0.3.0",
    "vue-slicezone": "^0.0.30"
  },
  "devDependencies": {
    "@nuxt/types": "^2.14.12",
    "@nuxt/typescript-build": "^2.0.4",
    "@nuxtjs/eslint-config-typescript": "^5.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/prismic": "^1.2.6",
    "@nuxtjs/storybook": "^3.3.1",
    "@nuxtjs/tailwindcss": "^4.0.2",
    "@tailwindcss/postcss7-compat": "^2.0.4",
    "autoprefixer": "^9.8.6",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.2",
    "eslint": "^7.18.0",
    "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-vue": "^7.5.0",
    "fibers": "^5.0.0",
    "node-sass": "^5.0.0",
    "sass": "^1.32.7",
    "sass-loader": "^10.1.1",
    "slice-machine-ui": "^0.0.45",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.4"
  }
}
```

**Comment by lihbr** [comment] 2021-03-30 07:34
Hey @lrocher91, thanks for opening an issue! Since you closed it I assume you figured out a workaround, let us know if anything!

**Comment by lrocher91** [comment] 2021-03-30 08:02
Hi,
Sorry i closed it because i don't know how to properly indent my code.
The issue is related to tailwind, it seems that they use `tailwindcss/postcss7-compat` package and it may cause issue with `@nuxt/postcss8` use by `vue-essential-slices`.
It's working if i remove tailwind packages. Still looking for a workaround, i'll let you know.

**Comment by lihbr** [comment] 2021-03-30 09:27
Ok, have no worries ☺️

Indeed Nuxt.js wasn't supporting PostCSS 8 until recently so to use Tailwind 2 you had to install: `autoprefixer@^9.0.0 postcss@^7.0.0 tailwindcss@npm:@tailwindcss/postcss7-compat` along `@nuxtjs/tailwindcss`.

However the latest version of Nuxt (`2.15.3`) now works with PostCSS 8 and `@nuxtjs/tailwindcss` has been updated to reflect that (you can even use [JIT](https://tailwindcss.nuxtjs.org/setup#tailwind-just-in-time)) Having TailwindCSS latest working with Nuxt.js should be a breeze on that point 🎉 

If you have any issue regarding Nuxt.js modules feel free to hope on [Nuxt.js Discord](https://discord.nuxtjs.org), there's a friendly community there always keen to help~

Also to display your code beautifully within GitHub issues (and MarkDown more generally), you need to wrap it within fences (3 backticks): ` ``` ` (`alggr+7` on Windows, don't know what on MacOS)

<pre>
```
Some code to highlight...
```
</pre>

Will produce:

```
Some code to highlight...
```

You can even have syntax highlight by specifying a language after the first fence:

<pre>
```javascript
console.log("Hello World");
```
</pre>

Will produce:

```javascript
console.log("Hello World");
```

Cheers!

**Comment by lrocher91** [comment] 2021-03-30 10:21
I tried to update to nuxt `2.15.3` to use PostCSS 8 but i'm getting the following error on `yarn generate` :

```
ERROR in ./node_modules/vue-essential-slices/src/styles/styles.scss (./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-essential-slices/src/styles/styles.scss)
Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) postcss-custom-properties: <css input> Unknown word

> 1 | var(--scale--small)*1*var(--scale--small)*var(--scale--small)*var(--scale--small)*var(--scale--small)
    | ^

 @ ./node_modules/vue-essential-slices/src/styles/styles.scss 4:14-251
 @ ./node_modules/.cache/nuxt/App.js
 @ ./node_modules/.cache/nuxt/index.js
 @ ./node_modules/.cache/nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/.cache/nuxt/client.js

ERROR in ./node_modules/vue-essential-slices/src/slices/CallToAction/index.vue?vue&type=style&index=0&id=25bc5f3e&lang=scss&scoped=true& (./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-essential-slices/src/slices/CallToAction/index.vue?vue&type=style&index=0&id=25bc5f3e&lang=scss&scoped=true&)
Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) postcss-custom-properties: <css input> Unknown word

> 1 | var(--scale--small)*1*var(--scale--small)*var(--scale--small)*var(--scale--small)*var(--scale--small)
    | ^

 @ ./node_modules/vue-essential-slices/src/slices/CallToAction/index.vue?vue&type=style&index=0&id=25bc5f3e&lang=scss&scoped=true& (./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-essential-slices/src/slices/CallToAction/index.vue?vue&type=style&index=0&id=25bc5f3e&lang=scss&scoped=true&) 4:14-480
 @ ./node_modules/vue-essential-slices/src/slices/CallToAction/index.vue?vue&type=style&index=0&id=25bc5f3e&lang=scss&scoped=true&
 @ ./node_modules/vue-essential-slices/src/slices/CallToAction/index.vue
 @ ./node_modules/vue-essential-slices/src/slices lazy ^\.\/.*\/index\.vue$ namespace object
 @ ./node_modules/.cache/nuxt/prismic/sm-resolver.js
 @ ./node_modules/.cache/nuxt/index.js
 @ ./node_modules/.cache/nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/.cache/nuxt/client.js

 FATAL  Nuxt build error                                                                                                                                                            12:17:41

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at processTicksAndRejections (node:internal/process/task_queues:94:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async ensureBuild (node_modules/@nuxt/cli/dist/cli-generate.js:145:3)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-generate.js:283:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here is my package.json :

```
{
  "name": "website",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt-ts",
    "build": "nuxt-ts build",
    "start": "nuxt-ts start",
    "generate": "nuxt-ts generate",
    "lint:js": "eslint --ext \".js,.vue\" --ignore-path .gitignore .",
    "lint": "yarn lint:js",
    "slicemachine": "start-slicemachine --port 9999",
    "storybook": "nuxt storybook",
    "build-storybook": "nuxt storybook build"
  },
  "dependencies": {
    "@nuxt/typescript-runtime": "^2.0.1",
    "@prismicio/vue": "^2.0.11",
    "core-js": "^3.9.1",
    "nuxt": "^2.15.3",
    "nuxt-sm": "^0.0.6",
    "prismic-javascript": "^3.0.2",
    "vue-essential-slices": "^0.3.0",
    "vue-slicezone": "^0.0.30"
  },
  "devDependencies": {
    "@nuxt/types": "^2.14.12",
    "@nuxt/typescript-build": "^2.0.4",
    "@nuxtjs/eslint-config-typescript": "^6.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/prismic": "^1.2.6",
    "@nuxtjs/storybook": "^3.3.1",
    "@nuxtjs/tailwindcss": "^4.0.2",
    "@tailwindcss/jit": "^0.1.17",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.2",
    "eslint": "^7.18.0",
    "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-vue": "^7.5.0",
    "fibers": "^5.0.0",
    "node-sass": "^5.0.0",
    "postcss": "^8.2.8",
    "postcss-nested": "^5.0.5",
    "slice-machine-ui": "^0.0.45"
  }
}

```

Thanks for your time 😉

**Comment by lihbr** [comment] 2021-03-30 10:27
Got it, looks like you're missing `sass-loader`, try installing it this way (I'm forcing the version since version 11 is broken with Vue renderer as of talking):
```
yarn add --dev sass-loader@^10.1.1
```

**Comment by lrocher91** [comment] 2021-03-30 11:12
It don't seems to be working, I removed yarn.lock, node_modules and i have the same issue. Here is ly updated package.json
```
{
  "name": "website",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt-ts",
    "build": "nuxt-ts build",
    "start": "nuxt-ts start",
    "generate": "nuxt-ts generate",
    "lint:js": "eslint --ext \".js,.vue\" --ignore-path .gitignore .",
    "lint": "yarn lint:js",
    "slicemachine": "start-slicemachine --port 9999",
    "storybook": "nuxt storybook",
    "build-storybook": "nuxt storybook build"
  },
  "dependencies": {
    "@nuxt/typescript-runtime": "^2.0.1",
    "@prismicio/vue": "^2.0.11",
    "core-js": "^3.9.1",
    "nuxt": "^2.15.3",
    "nuxt-sm": "^0.0.6",
    "prismic-javascript": "^3.0.2",
    "vue-essential-slices": "^0.3.0",
    "vue-slicezone": "^0.0.30"
  },
  "devDependencies": {
    "@nuxt/types": "^2.14.12",
    "@nuxt/typescript-build": "^2.0.4",
    "@nuxtjs/eslint-config-typescript": "^6.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/prismic": "^1.2.6",
    "@nuxtjs/storybook": "^3.3.1",
    "@nuxtjs/tailwindcss": "^4.0.2",
    "@tailwindcss/jit": "^0.1.17",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.2",
    "eslint": "^7.18.0",
    "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-vue": "^7.5.0",
    "fibers": "^5.0.0",
    "node-sass": "^5.0.0",
    "postcss": "^8.2.8",
    "postcss-nested": "^5.0.5",
    "sass-loader": "^10.1.1",
    "slice-machine-ui": "^0.0.45"
  }
}

```

**Comment by lihbr** [comment] 2021-03-30 11:23
Okay, is your repository open source by any chance? Or can you try to create a minimum reproduction? This will help us to figure out what's going on here 🙂

**Comment by lrocher91** [comment] 2021-03-30 11:28
I just created a public repo : 
https://github.com/lrocher91/nuxt-prismic-postcss

Thanks

**Comment by lihbr** [comment] 2021-03-30 12:04
Okay, looks like it was due to some overall dependencies being outdated. If you don't mind I went ahead and submitted a PR on your repo so you can have a look at changes made to get it working: https://github.com/lrocher91/nuxt-prismic-postcss/pull/1

**Comment by lrocher91** [comment] 2021-03-30 12:16
Many thanks you saved my day :)

**Closed** 2021-03-30 12:16 UTC

**Comment by lrocher91** [comment] 2021-04-01 10:35
I finally got it working by starting a new nuxt project from scratch. 
I updated the git repo ;)

**Comment by tomfri** [comment] 2021-09-17 11:50
The workaround for this is to add the following to nuxt.config.js...

```
build: {
	postcss: {
		plugins: {
			'postcss-custom-properties': false
		}
	}
}
```

**Comment by lihbr** [comment] 2021-09-17 12:11
Thanks for sharing @tomfri! 🙏 I'm sorry you had to run through those issues, if this library causes you issues you can also get rid of it if you don't use it ☺️

**Comment by stevebauman** [comment] 2021-11-14 17:10
Thank you SO much @tomfri!! Worked great for me! ❤️

**Comment by lukas-pierce** [comment] 2022-09-24 09:14
for me the solution was to change the order of multiplication in calc:

Old:

```css
img {
  margin: 1rem calc(var(--card-body-padding-x) * -1);
}
```

Replaced:

```css
img {
  margin: 1rem calc(-1 * var(--card-body-padding-x));
}
```

And after that the generation was successful. I think this only for calc with custom ccs properties
